#!/usr/bin/env python3

from threading import *
from np import shell
from np.core.np_main import start

def getpid():
	pid = None
	target1 = "python3"
	target2 = "/home/monkey/.local/bin/np"
	com = "pgrep -af python3"
	lines = shell(com).split("\n")
	ret = []
	for line in lines:
		if target1 in line and target2 in line:
			pid=line.split(" ")[0]
			ret.append(pid)
	return ret

pids = getpid()
if len(pids) < 2:
	isrunning = False
else:
	isrunning = True
if isrunning:
	import websocket
	c = websocket.create_connection('ws://192.168.2.2:8000/')
	c.send('create_gui')
	c.close()
	exit()

else:
	print ("starting")
	t = Thread(target = start)
	t.start()
