#!/bin/bash

if [ -n "$2" ]; then
	port="$2"
else
	read -p "Enter port:" port
fi
if [ -n "$1" ]; then
	host="$1"
else
	read -p "Enter player ip:" host
fi
data="
<html>
<head>
	<title>Simple client</title>
	<script type=\"text/javascript\">
		var ws;
		function init() {
			ws = new WebSocket(\"ws://$host:$port/\");
			ws.onopen = function() {
				output(\"onopen\");
			};
			ws.onmessage = function(e) {
				output(\"onmessage: \" + e.data);
			};
			ws.onclose = function() {
				output(\"onclose\");
			};
			ws.onerror = function(e) {
				output(\"onerror\");
				console.log(e)
			};
		}
		function onSubmit() {
			var input = document.getElementById(\"input\");
			ws.send(input.value);
			output(\"send: \" + input.value);
			input.value = \"\";
			input.focus();
		}
		function onCloseClick() {
			ws.close();
		}
		function output(str) {
			var log = document.getElementById(\"log\");
			var escaped = str.replace(/&/, \"&amp;\").replace(/</, \"&lt;\").
				replace(/>/, \"&gt;\").replace(/\"/, \"&quot;\"); // \"
			log.innerHTML = escaped + \"<br>\" + log.innerHTML;
		}
	</script>
</head>
<body onload=\"init();\">
	<form onsubmit=\"onSubmit(); return false;\">
		<input type=\"text\" id=\"input\">
		<input type=\"submit\" value=\"Send\">
		<button onclick=\"onCloseClick(); return false;\">close</button>
	</form>
	<div id=\"log\"></div>
</body>
</html>"
echo "$data" > "$HOME/.np/client.html"
