#!/usr/bin/env python3

from np import shell, COMFILE, EXEC_DIR
from np.core.np_main import start

def getpid():
	pid = None
	target1 = "python3 -c"
	target2 = "from np import server"
	target3 = "server.start"
	com = "pgrep -af python3"
	lines = shell(com).split("\n")
	for line in lines:
		if target1 in line and target2 in line and target3 in line:
			pid=line.split(" ")[0]
			return pid
	return pid

isrunning = getpid()

if isrunning is not None:
	#If running, assume gui open is needed.
	with open(COMFILE, "w") as f:
		f.write("create_gui")
	f.close()
elif isrunning is None:
	print ("starting")
	start()
