#!/usr/bin/env python3

import os
import subprocess
from np.core.core import shell, get_local_ip
from np.core.np import start
from threading import Thread

def getpid():
	_file = __file__
	if '/' in _file:
		_file = os.path.basename(_file)
	pid = None
	com = f"pgrep -af {_file} | grep -v \"/bin/sh\""
	lines = shell(com).split("\n")
	ret = []
	for line in lines:
		if 'np' in line:
			pid=line.split(" ")[0]
			ret.append(pid)
	return ret


def npexec():
	#com = f"np.bin&"
	com = f"python3 -c \"from np.core.np import start; start()\"&"
	subprocess.call(com, shell=True)

def ck_start():
	pids = getpid()
	if len(pids) < 2:
		isrunning = False
	else:
		isrunning = True
	if isrunning:
		import websocket
		localip = get_local_ip()
		try:
			conn = f"ws://{localip}:8000/"
			print("Conn:", conn)
			c = websocket.create_connection(conn)
			print("Connected:", c.connected)
			if c.connected is True:
				c.send('create_gui')
				c.close()
			else:
				print("Socket server not connected... Starting main")
				t = Thread(target=npexec)
				t.start()
		except Exception as e:
			print(f"Exception connecting to socket: {e}. Starting main")
			t = Thread(target=npexec)
			t.start()
	else:
		print ("starting")
		t = Thread(target=npexec)
		t.start()
ck_start()	
